version: "3"
services:
  db:
    image: postgres:12
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
    volumes:
      - db-data:/var/lib/postgresql/data
  cache:
    image: redis:6
    volumes:
      - cache-data:/data
  backend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
      - cache
  frontend:
    build: .
    ports:
      - "80:80"
    depends_on:
      - backend
    links:
      - backend
  proxy:
    image: nginx:1.19
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
    links:
      - frontend
volumes:
  db-data:
  cache-data:
